services:
  ctf:
    hostname: phoenixctf
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUID: "${CUID}"
        CGID: "${CGID}"
        SUID: "${SUID}"
        SGID: "${SGID}"
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - homes:/home
      - ./data:/home/user/ctf
      - roothome:/root
volumes:
  homes:

  roothome:
