services:
  ctf:
    hostname: phoenixctf
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        CUID: "${CUID}"
        CGID: "${CGID}"
        SUID: "${SUID}"
        SGID: "${SGID}"
        PARALLEL_BUILDS: "${PARALLEL_BUILDS}"
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - homes:/home
      - ./data:/home/user/ctf
volumes:
  homes:
    driver: local
